import React, { useState, useEffect, useMemo } from 'react';
import { auth, googleProvider } from './services/firebase';
import { signInWithPopup, signOut, onAuthStateChanged, User } from 'firebase/auth';
import Header from './components/Header';
import Navigation from './components/Navigation';
import StatsModal from './components/StatsModal';
import PronunciationModal from './components/PronunciationModal';
import ImportModal from './components/ImportModal';
import ReadingView from './views/ReadingView';
import ReviewView from './views/ReviewView';
import PracticeView from './views/PracticeView';
import GameView from './views/GameView';
import LabView from './views/LabView';
import CardsView from './views/CardsView';
import EmptyState from './components/EmptyState';
import { useStats } from './hooks/useStats';
import { useStudyItems } from './hooks/useStudyItems';
import { studyData as staticData } from './constants';
import { StudyItem } from './types';

const App: React.FC = () => {
    // Auth State
    const [user, setUser] = useState<User | null>(null);
    const [authLoading, setAuthLoading] = useState(true);

    // App State
    const [tab, setTab] = useState<string>('leitura');
    const [savedIds, setSavedIds] = useState<string[]>([]);
    const [showStats, setShowStats] = useState(false);
    const [showPronounce, setShowPronounce] = useState(false);
    const [showImport, setShowImport] = useState(false);
    
    // Hooks
    const { stats, recordResult, clearStats } = useStats();
    // Use Firestore hook connected to current user
    const { items: firebaseItems, addItem, deleteItem, loading: itemsLoading } = useStudyItems(user?.uid);

    // Auth Listener
    useEffect(() => {
        const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
            setUser(currentUser);
            setAuthLoading(false);
        });
        return () => unsubscribe();
    }, []);

    // Load Local Settings (Saved IDs)
    useEffect(() => {
        try {
            const localSaved = localStorage.getItem('mandarin_hsk_recovery');
            if (localSaved) {
                setSavedIds(JSON.parse(localSaved));
            }
        } catch (e) {
            console.error("Failed to load saved IDs", e);
        }
    }, []);

    // Combine Data (Static + Firebase)
    const libraryData = useMemo(() => {
        return [...firebaseItems, ...staticData];
    }, [firebaseItems]);

    // Handlers
    const handleLogin = async () => {
        try {
            await signInWithPopup(auth, googleProvider);
        } catch (error) {
            console.error("Login failed", error);
            alert("Erro ao conectar com Google.");
        }
    };

    const handleLogout = async () => {
        if (window.confirm("Deseja sair da conta?")) {
            await signOut(auth);
            setSavedIds([]); // Optional: clear local saved state on logout
        }
    };

    const toggleSave = (id: string) => {
        const newIds = savedIds.includes(id) 
            ? savedIds.filter(i => i !== id) 
            : [...savedIds, id];
        setSavedIds(newIds);
        localStorage.setItem('mandarin_hsk_recovery', JSON.stringify(newIds));
    };

    const handleImportBatch = async (newItems: StudyItem[]) => {
        if (!user) {
            alert("Você precisa estar logado para salvar textos na nuvem.");
            return;
        }
        
        // Iterate and add items one by one to Firestore
        // We strip the temporary ID generated by Gemini because Firestore creates its own
        for (const item of newItems) {
            // eslint-disable-next-line @typescript-eslint/no-unused-vars
            const { id, ...dataToSave } = item;
            await addItem(dataToSave);
        }
    };

    const handleDelete = async (id: string | number) => {
        if (typeof id === 'string') {
            await deleteItem(id);
        } else {
            alert("Não é possível deletar itens padrão do sistema.");
        }
    };

    // Render Logic
    if (authLoading) {
        return <div className="h-screen w-full flex items-center justify-center bg-slate-50 text-slate-400">Carregando...</div>;
    }

    const renderView = () => {
        if (!user && libraryData.length === 0) {
            return (
                <div className="flex flex-col items-center justify-center h-[70vh] text-center p-6">
                    <EmptyState msg="Bem-vindo ao MemorizaTudo" icon="brain-circuit" />
                    <p className="text-slate-500 mb-6 max-w-xs">Faça login para salvar seus textos, estudar e sincronizar seu progresso na nuvem.</p>
                    <button onClick={handleLogin} className="bg-brand-600 text-white px-6 py-3 rounded-full font-bold shadow-lg hover:bg-brand-700 transition-all">
                        Entrar com Google
                    </button>
                </div>
            );
        }

        switch (tab) {
            case 'leitura':
                return (
                    <ReadingView 
                        data={libraryData} 
                        savedIds={savedIds} 
                        onToggleSave={toggleSave} 
                        onOpenImport={() => setShowImport(true)}
                        onDeleteText={handleDelete}
                    />
                );
            case 'revisao':
                return <ReviewView data={libraryData} savedIds={savedIds} onRemove={toggleSave} />;
            case 'pratica':
                return <PracticeView data={libraryData} savedIds={savedIds} onResult={recordResult} />;
            case 'jogo':
                return <GameView data={libraryData} onResult={recordResult} />;
            case 'lab':
                return <LabView data={libraryData} savedIds={savedIds} onResult={recordResult} />;
            case 'cards':
                return <CardsView data={libraryData} savedIds={savedIds} onResult={recordResult} />;
            default:
                return null;
        }
    };

    return (
        <div className="h-[100dvh] flex flex-col bg-slate-50 w-full overflow-hidden relative">
            <Header 
                user={user}
                onLogin={handleLogin}
                onLogout={handleLogout}
                onOpenStats={() => setShowStats(true)} 
                onOpenPronounce={() => setShowPronounce(true)} 
            />
            
            <main className="flex-1 overflow-y-auto w-full no-scrollbar">
                <div className="max-w-3xl mx-auto h-full">
                    {itemsLoading && user ? (
                        <div className="p-10 text-center text-slate-300">Sincronizando...</div>
                    ) : (
                        renderView()
                    )}
                </div>
            </main>
            
            <Navigation activeTab={tab} onTabChange={setTab} />
            
            {showStats && (
                <StatsModal 
                    stats={stats} 
                    onClose={() => setShowStats(false)} 
                    onClear={clearStats} 
                />
            )}
            
            {showPronounce && (
                <PronunciationModal 
                    data={libraryData} 
                    onClose={() => setShowPronounce(false)} 
                    onResult={recordResult} 
                />
            )}

            {showImport && (
                <ImportModal 
                    onClose={() => setShowImport(false)}
                    onImport={handleImportBatch}
                />
            )}
        </div>
    );
};

export default App;