import React from 'react';
import {
    BookOpen,
    List,
    Edit3,
    Edit2,
    Gamepad2,
    FlaskConical,
    Layers,
    Mic,
    BarChart2,
    BrainCircuit,
    ChevronDown,
    ChevronRight,
    Trash2,
    BookmarkMinus,
    Bookmark,
    CheckCircle,
    X,
    Volume2,
    User,
    LogOut,
    Sparkles,
    Info,
    Plus,
    RotateCcw,
    Swords,
    Zap,
    Flame,
    Trophy,
    Download,
    Upload,
    Chrome,
    RefreshCw,
    Save,
    PlusCircle,
    Check,
    AlertCircle,
    LayoutGrid,
    Loader,
    Inbox,
    ArrowLeft,
    Maximize2,
    Minimize2,
    Folder,
    FolderTree,
    FolderPlus,
    Filter,
    Square,
    FolderInput,
    ArrowLeftRight,
    Search,
    ChevronUp,
    CornerDownRight,
    EyeOff,
    Activity,
    History,
    XCircle,
    ZoomIn,
    ZoomOut,
    Library,
    Maximize,
    SkipForward,
    Grid,
    ChevronLeft,
    Play,
    Clock,
    Ban,
    Star,
    Image,
    Brain,
    Palette,
    CalendarDays,
    BarChart3,
    Target,
    ArrowUpRight,
    ArrowUp,
    ArrowDown,
    Share2,
    Languages,
    Orbit,
    TrendingUp,
    Pause,
    SkipBack,
    Eye,
    MessageCircle
} from 'lucide-react';

export interface IconProps {
    name: string;
    size?: number;
    className?: string;
    fill?: string; // Adicionado para suportar preenchimento
}

const icons: Record<string, React.ElementType<any>> = {
    'book-open': BookOpen,
    'list': List,
    'edit-3': Edit3,
    'edit-2': Edit2,
    'gamepad-2': Gamepad2,
    'flask-conical': FlaskConical,
    'layers': Layers,
    'mic': Mic,
    'bar-chart-2': BarChart2,
    'brain-circuit': BrainCircuit,
    'chevron-down': ChevronDown,
    'chevron-right': ChevronRight,
    'trash-2': Trash2,
    'bookmark-minus': BookmarkMinus,
    'bookmark': Bookmark,
    'check-circle': CheckCircle,
    'x': X,
    'volume-2': Volume2,
    'user': User,
    'log-out': LogOut,
    'sparkles': Sparkles,
    'info': Info,
    'plus': Plus,
    'rotate-ccw': RotateCcw,
    'swords': Swords,
    'zap': Zap,
    'flame': Flame,
    'trophy': Trophy,
    'download': Download,
    'upload': Upload,
    'chrome': Chrome,
    'refresh-cw': RefreshCw,
    'save': Save,
    'plus-circle': PlusCircle,
    'check': Check,
    'alert-circle': AlertCircle,
    'layout-grid': LayoutGrid,
    'loader': Loader,
    'inbox': Inbox,
    'arrow-left': ArrowLeft,
    'maximize-2': Maximize2,
    'minimize-2': Minimize2,
    'folder': Folder,
    'folder-tree': FolderTree,
    'folder-plus': FolderPlus,
    'filter': Filter,
    'square': Square,
    'folder-input': FolderInput,
    'arrow-left-right': ArrowLeftRight,
    'search': Search,
    'chevron-up': ChevronUp,
    'corner-down-right': CornerDownRight,
    'eye-off': EyeOff,
    'activity': Activity,
    'history': History,
    'x-circle': XCircle,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
    'library': Library,
    'maximize': Maximize,
    'skip-forward': SkipForward,
    'grid': Grid,
    'chevron-left': ChevronLeft,
    'play': Play,
    'clock': Clock,
    'ban': Ban,
    'star': Star,
    'image': Image,
    'brain': Brain,
    'palette': Palette,
    'calendar-days': CalendarDays,
    'bar-chart-3': BarChart3,
    'target': Target,
    'arrow-up-right': ArrowUpRight,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'share-2': Share2,
    'languages': Languages,
    'orbit': Orbit,
    'trending-up': TrendingUp,
    'pause': Pause,
    'skip-back': SkipBack,
    'eye': Eye,
    'message-circle': MessageCircle
};

const Icon: React.FC<IconProps> = ({ name, size = 24, className = '', fill = 'none' }) => {
    const LucideIcon = icons[name] as any;

    if (!LucideIcon) {
        console.warn(`Icon "${name}" not found`);
        return null;
    }

    return <LucideIcon size={size} className={className} fill={fill} />;
};

export default Icon;