import React from 'react';
import { StudyItem, SupportedLanguage } from '../../types';
import { ColorCorrectionToken } from '../../services/localDB';
import { DifficultyLevel } from './newWordsUtils';
import { useReadingComments } from './useReadingComments';

export interface ReadingChromeProps {
    filteredData: StudyItem[];
    studyListLength: number;
    activeFolderFilters: string[];
    onUpdateFolderFilters: (filters: string[]) => void;
    readingMode: 'study' | 'simple';
    setReadingMode: (mode: 'study' | 'simple') => void;
    readingPrefs: { showTranslation: boolean; fontSize: 'sm' | 'md' | 'lg' | 'xl' };
    setReadingPrefs: (prefs: { showTranslation: boolean; fontSize: 'sm' | 'md' | 'lg' | 'xl' } | ((prev: { showTranslation: boolean; fontSize: 'sm' | 'md' | 'lg' | 'xl' }) => { showTranslation: boolean; fontSize: 'sm' | 'md' | 'lg' | 'xl' })) => void;
    focusNewWords: boolean;
    setFocusNewWords: (fn: boolean | ((v: boolean) => boolean)) => void;
    difficultyFilter: DifficultyLevel | 'all';
    setDifficultyFilter: (v: DifficultyLevel | 'all') => void;
    difficultyCounts: { easy: number; medium: number; hard: number };
    selectionMode: boolean;
    reorderMode: boolean;
    selectedIds: Set<string>;
    showColorPopover: boolean;
    isCorrectingColors: boolean;
    isColorHighlightEnabled: boolean;
    colorBtnRef: React.RefObject<HTMLButtonElement | null>;
    colorPopoverRef: React.RefObject<HTMLDivElement | null>;
    colorCorrections: Map<string, ColorCorrectionToken[]>;
    selectedStudyFolder: string | null;
    nativeLessonId: string | null;
    nativeAudio: any;
    splitAudioCue: { audioLessonId: string; start: number; end: number } | null;
    attachingAudio: boolean;
    introSkip: number;
    alignmentCount: number;
    commentsApi: ReturnType<typeof useReadingComments>;
    speakText: (text: string, language: SupportedLanguage, id?: string) => Promise<void>;
    stopAllSpeech: () => void;
    playingId?: string | null;
    onAttachFolderAudio?: (file: File) => Promise<void>;
    handleAttachFolderAudio: (file: File) => Promise<void>;
    onCorrectColors: (ids?: string[]) => void;
    setShowColorPopover: (v: boolean) => void;
    setIsColorHighlightEnabled: (v: boolean) => void;
    setSelectionMode: (v: boolean) => void;
    setReorderMode: (v: boolean) => void;
    setLocalReorderData: (data: StudyItem[]) => void;
    cancelSelection: () => void;
    cancelReorder: () => void;
    saveReorder: () => void;
    selectAll: () => void;
    handleEditSelected: () => void;
    handleDeleteSelected: () => void;
    openMoveModal: () => void;
    setShowExportModal: (v: boolean) => void;
    setShowNativeAudioModal: (v: boolean) => void;
    setShowAlignmentModal: (v: boolean) => void;
    onDeleteText?: (id: string | number) => void;
    onDeleteMany?: (ids: (string | number)[]) => Promise<void>;
}
